# ==============================================================================
# docker-compose
# ==============================================================================
version: '2'
services:
  app:
    build: .
    command: bundle exec ruby app.rb -o 0.0.0.0
    ports:
      - 8080:4567
    volumes:
      - .:/usr/local/pdf_presenter
      - bundle-data:/usr/local/bundle
volumes:
  bundle-data: {}
